In [1]:
import numpy as np

In [2]:
n=np.array([[1,2,3,4],[11,22,33,40],[5,7,9,90]])

In [3]:
n[0,0]

1

In [4]:
n[1,2]

33

In [5]:
n[2][:2]

array([5, 7])

In [7]:
n[2,:2]

array([5, 7])

In [8]:
n[2,2:]

array([ 9, 90])

In [10]:
n

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

In [11]:
n.shape

(3, 4)

In [12]:
n[0,0]

1

In [13]:
n[2,1:3]

array([7, 9])

In [14]:
n[1:3,2:4]

array([[33, 40],
       [ 9, 90]])

In [15]:
n[1:,2:]

array([[33, 40],
       [ 9, 90]])

In [16]:
n[1,:2]

array([11, 22])

In [19]:
n[:,3:]

array([[ 4],
       [40],
       [90]])

In [22]:
np.arange(4.5,50.3)

array([ 4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5,
       15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5,
       26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5,
       37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5,
       48.5, 49.5])

# Reshape

In [23]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
np.sqrt(81)

9.0

In [30]:
np.max(n)

90

n.min()

In [31]:
n.max()


90

In [32]:
n.min()

1

In [33]:
n.mean()

18.916666666666668

In [34]:
n.argmin()

0

In [35]:
n.argmax()

11

In [36]:
n

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

In [37]:
n*2

array([[  2,   4,   6,   8],
       [ 22,  44,  66,  80],
       [ 10,  14,  18, 180]])

In [38]:
n+10

array([[ 11,  12,  13,  14],
       [ 21,  32,  43,  50],
       [ 15,  17,  19, 100]])

In [39]:
n.sort()

In [40]:
n

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

In [41]:
n.sort()

In [42]:
n

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

# Random

In [43]:
np.random.rand(2,2)

array([[0.86136822, 0.18083827],
       [0.47889536, 0.78574826]])

In [44]:
np.random.rand(2)

array([0.72550147, 0.76211119])

In [45]:
np.random.randn(2,2)

array([[ 0.1682984 ,  1.4808819 ],
       [-0.25017812, -1.01304247]])

In [47]:
np.random.randint(9,90,12)

array([37, 20, 19, 26, 46, 76, 53, 45, 49, 23, 73, 63])

In [49]:
s=np.random.randint(9,90,12).reshape(6,2)

In [50]:
s

array([[43, 82],
       [55, 15],
       [62, 38],
       [64, 57],
       [ 9, 13],
       [50,  9]])

In [51]:
s.sum()

497

In [52]:
s.sum(axis=1)

array([125,  70, 100, 121,  22,  59])

# 3D


In [54]:
t=np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,50],[4,40],[6,60]]])

In [55]:
t


array([[[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 5, 50],
        [ 4, 40],
        [ 6, 60]]])

In [57]:
t.shape

(3, 3, 2)

In [58]:
#Nan -not a number

In [59]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [60]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [64]:
x.dtype

dtype('float64')

In [68]:
t=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[2,3,4,5],[4,5,6,7],[6,7,8,9]]])

In [69]:
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 2,  3,  4,  5],
        [ 4,  5,  6,  7],
        [ 6,  7,  8,  9]]])

In [70]:
t.shape

(4, 3, 4)